import Head from "next/head";

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About Us | Murat Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda consequuntur dolore eligendi nisi, quos veniam veritatis. A at consectetur, deleniti doloribus enim expedita, fugiat harum ipsum perferendis quaerat quibusdam quo, repudiandae similique tenetur totam veniam vitae? Eaque ipsa itaque obcaecati repellendus similique! Aspernatur cum distinctio enim ipsum nemo suscipit vero.</div>
    </>
  )
}

export default AboutUs;
