import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import List from "../components/List";
import Page from "../components/Page";
import { useContext } from "react";
import { MoviesContext } from "../contexts/movies-context";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { movies } = useContext(MoviesContext);

  return (
    <>
      <Head>
        <title>Home | Murat Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.description}>
          <div className={`row py-lg-5 ${styles.code}`}>
            <div className="col-lg-6 col-md-8 mx-auto">
              <h1 className="fw-light">Album example</h1>
              <p className="lead text-muted">Something short and leading about the collection below—its contents, the
                creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it
                entirely.</p>
              <p>
                <a
                  href="#"
                  className="btn btn-primary my-2"
                  onClick={() => setFullName("Ömer Öztürk")}
                >Main call to action</a>
                <a href="#" className="btn btn-secondary my-2">Secondary action</a>
              </p>
            </div>
          </div>
        </section>

        <div className="album py-5 bg-light">
          <div className="container">

            <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
              {movies?.map((movie, index) => (
                <List
                  key={index}
                  movie={movie}
                />
              ))}
            </div>
          </div>

          <Page />
        </div>
      </main>
    </>
  )
}
